######################################################################
# Automatically generated by qmake (1.07a) Fri Jul 16 09:09:25 2010
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
INTERFACES += mainform.ui
SOURCES += main.cpp
